# Generated by Django 5.2 on 2025-05-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Event', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventparticipant',
            options={'ordering': ['joined_at'], 'verbose_name': 'Event Participant', 'verbose_name_plural': 'Event Participants'},
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='check_in_time',
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='waitlist_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
