# Generated by Django 5.2 on 2025-05-26 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Event', '0002_initial'),
        ('App_Payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Event.event'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='event_participant',
            field=models.ForeignKey(blank=True, help_text='Event participant record associated with this payment intent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='App_Event.eventparticipant'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intent', to='App_Payment.payment'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user'], name='App_Payment_user_id_990a21_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['event'], name='App_Payment_event_i_d0831e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status'], name='App_Payment_payment_9acf9b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='App_Payment_created_e0a7ce_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='App_Payment_transac_ff730c_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('user', 'event', 'event_participant'), name='unique_payment_per_user_event_participant'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'status'), name='unique_active_subscription_per_user'),
        ),
    ]
